# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      # Runs a set of commands using the runners shell
      - name: Install Python
        run: |
          python3 -m pip install --upgrade pip
          python3 -m pip install virtualenv
      - name: Setup carton-labels for deployment
        run: |
          filepath=`pwd`
          projectFolder="carton-labels"
          cd $projectFolder
          python3 -m venv env
          source env/bin/activate
          python3 -m pip install -r requirements.txt
          cp *.ttf $filepath/$projectFolder/env/lib/python3.8/site-packages
          cp *.py $filepath/$projectFolder/env/lib/python3.8/site-packages
          cd $filepath/$projectFolder/env/lib/python3.8/site-packages
          zip -r lambda_function.zip .
          rm -f lambda_funcation.zip
          cp *.zip $filepath
      - name: deploy carton-labels to lambda
        uses: appleboy/lambda-action@master
        with:
          aws_access_key_id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws_secret_access_key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws_region: us-east-1
          function_name: test2
          zip_file: lambda_function.zip
          memory_size: 512
          timeout: 600
          handler: lambda_function.lambda_handler
          runtime: python3.8
      - name: Setup invoice_pdf_creation for deployment
        run: |
          filepath=`pwd`
          projectFolder="invoice_pdf_creation"
          cd $projectFolder
          python3 -m venv env
          source env/bin/activate
          python3 -m pip install -r requirements.txt
          cp *.html $filepath/$projectFolder/env/lib/python3.8/site-packages
          cp *.txt $filepath/$projectFolder/env/lib/python3.8/site-packages
          cp *.py $filepath/$projectFolder/env/lib/python3.8/site-packages
          cp -R fonts $filepath/$projectFolder/env/lib/python3.8/site-packages
          cd $filepath/$projectFolder/env/lib/python3.8/site-packages
          zip -r lambda_function.zip .
          rm -f lambda_funcation.zip
          cp *.zip $filepath
      - name: deploy invoice_pdf_creation to lambda
        uses: appleboy/lambda-action@master
        with:
          aws_access_key_id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws_secret_access_key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws_region: us-east-1
          function_name: test1
          zip_file: lambda_function.zip
          memory_size: 512
          timeout: 600
          environment: FONTCONFIG_PATH=/var/task/fonts,S3BUCKET_NAME=test12345test123
          handler: lambda_function.lambda_handler
          runtime: python3.8
